# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file (generated by Gradle) into the container
COPY build/libs/testBangalore-1.0.0.jar app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
# Expose the port your app will run on

EXPOSE 8080
