name: Build and Push Docker Image

# Trigger the workflow when there's a push to the main branch
on:
  push:
   branches:
      - main # Replace with your branch name if different

jobs:
  build:
   runs-on: ubuntu-latest # Using the latest Ubuntu runner for the build environment

   steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub using GitHub secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username stored in secrets
        password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password stored in secrets

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/testBangalore:latest

  # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/testBangalore:latest

