name: Build and Push Docker Image

# Trigger the workflow on pushes to the main branch
on:
 push:
 branches:
 - main

jobs:
 build:
 # Use the latest Ubuntu runner
 runs-on: ubuntu-latest

 steps:
 # Step 1: Check out the code from the repository
 - name: Check out repository
 uses: actions/checkout@v3

 # Step 2: Set up Docker Buildx
 - name: Set up Docker Buildx
 uses: docker/setup-buildx-action@v2

 # Step 3: Log in to Docker Hub
 - name: Log in to Docker Hub
 uses: docker/login-action@v2
 with:
 username: ${{ secrets.DOCKER_USERNAME }}
 password: ${{ secrets.DOCKER_PASSWORD }}

 # Step 4: Build and tag the Docker image
 - name: Build Docker image
 run: |
 docker build -t meghajayanna/bangalore-restaurants:latest .

 # Step 5: Push the Docker image to Docker Hub
 - name: Push Docker image
 run: |
 docker push meghajayanna/bangalore-restaurants:latest
