name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

    # Step 2: Set up JDK 17 for building the Java application
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'termurin'

    # Step 3: Build the application with Gradle
      - name: Build with Gradle
        run: ./gradlew build

    # Step 4: List files in build/libs (to confirm .jar file exists)
      - name: List files in build/libs
        run: ls build/libs

    # Step 5: Log into Docker Hub
      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bangalore-restaurants:latest
          build-args: |
            --no-cache