name: Build and Push Docker Image

# Trigger the workflow when there's a push to the main branch
on:
  push:
    branches:
      - main # Replace with your branch name if different

permissions:
  contents: read

jobs:
  ci-job:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout to repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.branch }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username stored in secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password stored in secrets
      - name: Print Hello
        run: echo "Hello World"